from src.storage.checkpoints import (
    analysis_dir,
    cross_dataset_dir,
    load_state_dict,
    metadata_dir,
    save_state_dict,
    student_dir,
    teacher_dir,
)
from src.config import Config
from src.runspec import RunSpec, load_run_spec, run_spec_from_mapping
from src.distill.conditions import (
    ConditionSpec,
    all_conditions,
    condition_from_flags,
)
from src.data.datasets import (
    ALL_DATASETS,
    DATASET_ANLI,
    DATASET_DAVIDSON,
    DATASET_DYNAHATE,
    DATASET_FEVER,
    DATASET_HATEVAL,
    DATASET_IMDB,
    DATASET_TWEETEVAL_SENTIMENT,
    DATASET_VARDIAL,
    DatasetSpec,
    LocalCsvSource,
    SentimentLabel,
    build_loader,
    dataset_by_name,
    encode_batch,
    load_split,
    source_fingerprint,
)
from src.pipeline.earlystop import EarlyStopper
from src.eval import (
    EvaluationResult,
    TeacherStudentAnalysis,
    collect_probabilities,
    compute_teacher_student_analysis,
    evaluate,
)
from src.distill.losses import attention_kd_loss, compute_student_losses, hidden_kd_loss, logit_kd_loss
from src.modeling.models import load_tokenizer, load_classifier
from src.modeling.projections import HiddenProjection
from src.storage.runlog import (
    RunMetadata,
    TrainEpochEntry,
    collect_hardware,
    make_run_id,
    write_run_metadata,
)
from src.pipeline.teacher import (
    TeacherData,
    TeacherEvaluationResult,
    TeacherEpochStats,
    TeacherModel,
    TeacherTrainingResult,
    configure_reproducibility,
    evaluate_saved_teacher,
    fine_tune_teacher,
    format_teacher_eval_summary,
    load_teacher_data,
    load_trained_teacher,
    prepare_teacher_model,
    resolve_device,
    save_teacher_evaluation_result,
    save_teacher_training_result,
    start_teacher_metadata,
    train_teacher_epoch,
)
from src.pipeline.student import (
    StudentData,
    StudentEpochStats,
    StudentEvaluationResult,
    StudentModel,
    StudentTrainingResult,
    evaluate_saved_student,
    fine_tune_student,
    format_student_eval_summary,
    load_student_data,
    prepare_student_model,
    save_student_evaluation_result,
    save_student_training_result,
    start_student_metadata,
    train_student_epoch,
)
from src.utils import (
    clone_state_dict_cpu,
    count_params,
    move_batch_to_device,
    training_autocast,
)

__all__ = [
    # config
    "Config",
    "RunSpec",
    "load_run_spec",
    "run_spec_from_mapping",
    # datasets
    "DatasetSpec",
    "LocalCsvSource",
    "SentimentLabel",
    "DATASET_TWEETEVAL_SENTIMENT",
    "DATASET_IMDB",
    "DATASET_ANLI",
    "DATASET_DAVIDSON",
    "DATASET_DYNAHATE",
    "DATASET_FEVER",
    "DATASET_HATEVAL",
    "DATASET_VARDIAL",
    "ALL_DATASETS",
    "dataset_by_name",
    "build_loader",
    "encode_batch",
    "load_split",
    "source_fingerprint",
    # conditions
    "ConditionSpec",
    "condition_from_flags",
    "all_conditions",
    # eval
    "EvaluationResult",
    "TeacherStudentAnalysis",
    "collect_probabilities",
    "compute_teacher_student_analysis",
    "evaluate",
    # models / losses
    "attention_kd_loss",
    "compute_student_losses",
    "hidden_kd_loss",
    "logit_kd_loss",
    "load_tokenizer",
    "load_classifier",
    "HiddenProjection",
    # runlog
    "RunMetadata",
    "TrainEpochEntry",
    "make_run_id",
    "collect_hardware",
    "write_run_metadata",
    # teacher pipeline
    "TeacherData",
    "TeacherEvaluationResult",
    "TeacherEpochStats",
    "TeacherModel",
    "TeacherTrainingResult",
    "configure_reproducibility",
    "evaluate_saved_teacher",
    "fine_tune_teacher",
    "format_teacher_eval_summary",
    "load_teacher_data",
    "load_trained_teacher",
    "prepare_teacher_model",
    "resolve_device",
    "save_teacher_evaluation_result",
    "save_teacher_training_result",
    "start_teacher_metadata",
    "train_teacher_epoch",
    # student pipeline
    "StudentData",
    "StudentEpochStats",
    "StudentEvaluationResult",
    "StudentModel",
    "StudentTrainingResult",
    "evaluate_saved_student",
    "fine_tune_student",
    "format_student_eval_summary",
    "load_student_data",
    "prepare_student_model",
    "save_student_evaluation_result",
    "save_student_training_result",
    "start_student_metadata",
    "train_student_epoch",
    # checkpoints / paths
    "teacher_dir",
    "student_dir",
    "metadata_dir",
    "analysis_dir",
    "cross_dataset_dir",
    "save_state_dict",
    "load_state_dict",
    # earlystop
    "EarlyStopper",
    # utils
    "count_params",
    "move_batch_to_device",
    "training_autocast",
    "clone_state_dict_cpu",
]
